version: "3.8"

services:
  mongodb:
    image: registry.docker-cn.com/library/mongo:6.0
    container_name: werewolf-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: always

volumes:
  mongodb_data:
